/**
 * Centralized error codes for the entire ARISA Cloud Backend.
 * Format: {DOMAIN}_{ERROR_TYPE}
 *
 * These codes are returned in error responses and used by
 * the mobile app / Pi to handle errors programmatically.
 */
export enum ErrorCode {
  // ─── Auth ───────────────────────────────────────────────
  AUTH_EMAIL_EXISTS = 'AUTH_EMAIL_EXISTS',
  AUTH_INVALID_CREDENTIALS = 'AUTH_INVALID_CREDENTIALS',
  AUTH_TOKEN_MISSING = 'AUTH_TOKEN_MISSING',
  AUTH_TOKEN_INVALID = 'AUTH_TOKEN_INVALID',
  AUTH_TOKEN_EXPIRED = 'AUTH_TOKEN_EXPIRED',
  AUTH_REFRESH_TOKEN_INVALID = 'AUTH_REFRESH_TOKEN_INVALID',
  AUTH_UNAUTHORIZED = 'AUTH_UNAUTHORIZED',
  AUTH_FORBIDDEN = 'AUTH_FORBIDDEN',
  AUTH_ACCOUNT_SUSPENDED = 'AUTH_ACCOUNT_SUSPENDED',
  AUTH_USER_NOT_FOUND = 'AUTH_USER_NOT_FOUND',

  // ─── Device ─────────────────────────────────────────────
  DEVICE_NOT_FOUND = 'DEVICE_NOT_FOUND',
  DEVICE_ALREADY_PAIRED = 'DEVICE_ALREADY_PAIRED',
  DEVICE_PAIRING_CODE_INVALID = 'DEVICE_PAIRING_CODE_INVALID',
  DEVICE_PAIRING_CODE_EXPIRED = 'DEVICE_PAIRING_CODE_EXPIRED',
  DEVICE_TOKEN_MISSING = 'DEVICE_TOKEN_MISSING',
  DEVICE_TOKEN_INVALID = 'DEVICE_TOKEN_INVALID',
  DEVICE_SERIAL_MISSING = 'DEVICE_SERIAL_MISSING',
  DEVICE_DISABLED = 'DEVICE_DISABLED',
  DEVICE_REVOKED = 'DEVICE_REVOKED',
  DEVICE_REGISTRATION_SECRET_INVALID = 'DEVICE_REGISTRATION_SECRET_INVALID',
  DEVICE_SERIAL_EXISTS = 'DEVICE_SERIAL_EXISTS',

  // ─── Sync ───────────────────────────────────────────────
  SYNC_DUPLICATE_REQUEST = 'SYNC_DUPLICATE_REQUEST',
  SYNC_PAYLOAD_INVALID = 'SYNC_PAYLOAD_INVALID',
  SYNC_JOB_NOT_FOUND = 'SYNC_JOB_NOT_FOUND',
  SYNC_BATCH_TOO_LARGE = 'SYNC_BATCH_TOO_LARGE',
  SYNC_CONFLICT = 'SYNC_CONFLICT',
  SYNC_OWNERSHIP_MISMATCH = 'SYNC_OWNERSHIP_MISMATCH',

  // ─── Data ───────────────────────────────────────────────
  DATA_NOT_FOUND = 'DATA_NOT_FOUND',
  DATA_OWNERSHIP_DENIED = 'DATA_OWNERSHIP_DENIED',

  // ─── Notification ───────────────────────────────────────
  NOTIFICATION_NOT_FOUND = 'NOTIFICATION_NOT_FOUND',

  // ─── AI ─────────────────────────────────────────────────
  AI_PROVIDER_UNAVAILABLE = 'AI_PROVIDER_UNAVAILABLE',
  AI_QUOTA_EXCEEDED = 'AI_QUOTA_EXCEEDED',
  AI_REQUEST_FAILED = 'AI_REQUEST_FAILED',

  // ─── Weather ──────────────────────────────────────────────
  WEATHER_API_NOT_CONFIGURED = 'WEATHER_API_NOT_CONFIGURED',
  WEATHER_FETCH_FAILED = 'WEATHER_FETCH_FAILED',
  WEATHER_API_UNAUTHORIZED = 'WEATHER_API_UNAUTHORIZED',
  WEATHER_RATE_LIMITED = 'WEATHER_RATE_LIMITED',
  WEATHER_INVALID_COORDINATES = 'WEATHER_INVALID_COORDINATES',
  WEATHER_MISSING_PARAMS = 'WEATHER_MISSING_PARAMS',

  // ─── Sawah ────────────────────────────────────────────────
  SAWAH_NOT_FOUND = 'SAWAH_NOT_FOUND',
  SAWAH_OWNERSHIP_DENIED = 'SAWAH_OWNERSHIP_DENIED',

  // ─── System ─────────────────────────────────────────────
  SYSTEM_INTERNAL_ERROR = 'SYSTEM_INTERNAL_ERROR',
  SYSTEM_SERVICE_UNAVAILABLE = 'SYSTEM_SERVICE_UNAVAILABLE',
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  RATE_LIMIT_EXCEEDED = 'RATE_LIMIT_EXCEEDED',
  RESOURCE_NOT_FOUND = 'RESOURCE_NOT_FOUND',
  RESOURCE_CONFLICT = 'RESOURCE_CONFLICT',
}
