import {
  Controller,
  Post,
  Get,
  Param,
  Body,
  Query,
  UseGuards,
  HttpCode,
  HttpStatus,
} from '@nestjs/common';
import {
  ApiTags,
  ApiOperation,
  ApiResponse,
  ApiSecurity,
  ApiQuery,
} from '@nestjs/swagger';
import { SyncService } from './sync.service';
import { SyncPushDto, SyncBatchDto, SyncAckDto, SessionSummaryDto } from './dto';
import { DeviceAuthGuard } from '../../common/guards/device-auth.guard';
import { CurrentDevice } from '../../common/decorators/current-device.decorator';

@ApiTags('Sync')
@Controller('sync')
@UseGuards(DeviceAuthGuard)
@ApiSecurity('device-token')
export class SyncController {
  constructor(private readonly syncService: SyncService) {}

  @Post('push')
  @HttpCode(HttpStatus.ACCEPTED)
  @ApiOperation({ summary: 'Push single sync item from device' })
  @ApiResponse({ status: 202, description: 'Job accepted for processing' })
  async push(
    @Body() dto: SyncPushDto,
    @CurrentDevice('id') deviceId: string,
  ) {
    return this.syncService.push(dto, deviceId);
  }

  @Post('batch')
  @HttpCode(HttpStatus.ACCEPTED)
  @ApiOperation({ summary: 'Push batch of sync items (max 100)' })
  @ApiResponse({ status: 202, description: 'Batch accepted' })
  async batch(
    @Body() dto: SyncBatchDto,
    @CurrentDevice('id') deviceId: string,
  ) {
    return this.syncService.pushBatch(dto, deviceId);
  }

  @Get('status/:jobId')
  @HttpCode(HttpStatus.OK)
  @ApiOperation({ summary: 'Check sync job status' })
  @ApiResponse({ status: 200, description: 'Job status returned' })
  @ApiResponse({ status: 404, description: 'Job not found' })
  async status(@Param('jobId') jobId: string) {
    return this.syncService.getJobStatus(jobId);
  }

  @Post('ack')
  @HttpCode(HttpStatus.OK)
  @ApiOperation({ summary: 'Acknowledge synced items' })
  @ApiResponse({ status: 200, description: 'Acknowledged count' })
  async ack(@Body() dto: SyncAckDto) {
    return this.syncService.acknowledge(dto);
  }

  @Get('pull')
  @HttpCode(HttpStatus.OK)
  @ApiOperation({ summary: 'Pull updates from cloud to device' })
  @ApiQuery({ name: 'since', description: 'ISO 8601 timestamp', required: true })
  @ApiQuery({ name: 'limit', description: 'Max items', required: false })
  @ApiResponse({ status: 200, description: 'Items to sync' })
  async pull(
    @Query('since') since: string,
    @Query('limit') limit?: number,
    @CurrentDevice('ownerIds') ownerIds?: string[],
  ) {
    // B4: Filter by device's owner(s) to prevent cross-user data leaks
    const userId = ownerIds?.[0]; // Primary owner
    return this.syncService.pull(since, limit ? Number(limit) : 50, userId);
  }

  // ─── Session Summary (IoT Context for AI) ───────────────

  @Post('session-summary')
  @HttpCode(HttpStatus.CREATED)
  @ApiOperation({
    summary: 'Push IoT session summary from edge AI',
    description:
      'Ingests a session summary generated by the Raspberry Pi edge AI. ' +
      'These summaries are automatically injected into cloud AI context ' +
      'when a user chats with deviceId parameter.',
  })
  @ApiResponse({ status: 201, description: 'Session summary ingested' })
  async pushSessionSummary(
    @Body() dto: SessionSummaryDto,
    @CurrentDevice('id') deviceId: string,
  ) {
    return this.syncService.ingestSessionSummary(dto, deviceId);
  }
}
